require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

target 'ios_simulator_build' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false
  )

  target 'ios_simulator_buildTests' do
    inherit! :complete
  end

  # Flipper disabled because older Flipper-Glog fails on modern Xcode/Apple Silicon
  # use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    
    # Fix for Boost 1.76.0 compatibility with C++17+ (std::unary_function removed)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['GCC_WARN_ABOUT_DEPRECATED_FUNCTIONS'] = 'NO'
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '-Wno-deprecated-declarations'
      end
    end
  end
end